### ISSUE TITLE
CalDAV Sync

### ISSUE THREAD

**Issue by cbix** [spacecowboy/NotePad#120]
CalDAV synchronization of notes/todos would be an awesome feature. CalDAV works with VEVENT/VTODO standards so we need a parser first…

**Comment by CampelloManuel** [comment]
I will download some calendar apps from f-droid and see what we can do to implement some sort of calendar sync with the available technology

**Comment by CampelloManuel** [comment]
I found https://manual.davx5.com/introduction.html which explains how we should setup CalDAV in the app.

Basically we need to interface with the android calendar provider, and then apps like "DAVx5" ( https://f-droid.org/it/packages/at.bitfire.davdroid/ ) will synchronize the android calendar to a server.

Since an interface with the android calendar provider is already tracked in #387 this issue is outdated
