### ISSUE TITLE
Phone number highlighter too agressive

### ISSUE THREAD

**Issue by Ziphilt** [spacecowboy/NotePad#256]
When typing notes, the app recognizes things like

```
12--78 -2
1.3 2.4 3
```

as phone numbers. With a bit of testing, it accepts series of at least five numbers, with no maximum, separated by any number of spaces, periods, or hyphens, and also some handling of parentheses at the beginning. This is annoying because it means I can't place the cursor in the numbers it thinks are a phone number, as it instead offers to call or text the number. I don't actually even use this app in a way that requires me to look up phone numbers, so an option to disable this highlighting would satisfy me.

**Comment by CampelloManuel** [comment]
As of version 7.1.6, this app:
* will highlight phone numbers both on the list view and the note detail view
* will consider any number with more than 7 digits as a phone number, as explained by the OP
* has 2 toggles in the settings to disable the phone number highlight behavior, both for the list  viewand for the note detail view

Since this behavior can be disabled with good granularity, I consider this problem solved
