### ISSUE TITLE
Tasks appearing, disappearing, being duplicated [data loss]

### ISSUE THREAD

**Issue by devurandom** [spacecowboy/NotePad#276]
Today I noticed several odd behaviours with my tasks:
* First they were all gone. Shocking experience, to say the least…
  * Luckily I was able to recover the most important ones from the Archive.
* Accidentally I added several duplicates, because the Archive apparently stores lots and lots of duplicates of each task (one each time the tasks are being synced?). Thus I had to delete the duplicates manually.
* Then a few moments later, suddenly all tasks were gone again.
* Then they suddenly reappeared, but this time with about 10 duplicates for each.
* I rebooted the phone and then manually deleted every copy.
* Let's see what happens next…

This used to work better. Before the last update(s), I did not notice any issues with syncing or data loss.

**Comment by goncalopp** [comment]
I'm also experiencing this. Items are randomly deleted and duplicated while presumably syncing to SD ("Loading" on top of app). This happens multiple times while the app is open. Sometimes the duplicates disappear.

The SD file show **multiple duplicated entries with different IDs**. Maybe it's confused because of that, but I have no idea how it got this way in the first place. I did not edit the file before noticing the problem.

I have version 5.5.4, presumably from the market. Problem didn't happen in F-droid version yet (just tested it).

I have a file sync service, but it hasn't modified the file, AFAICT. I never restored backups.

**Comment by spacecowboy** [comment]
@goncalopp Thanks for adding your experiences. I'm having trouble pinning down this issue because there seems to be a random element to it. 

About non-ascii characters, they shouldn't factor in but what could you give an example word?

**Comment by goncalopp** [comment]
A example would be "avó"

I haven't been able to reproduce this again since installing F-droid 5.5.3
