### ISSUE TITLE
How to add location based reminder

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/NotePad#301]
I keep seeing this image: https://github.com/spacecowboy/NotePad/blob/master/phone.png but I don't know how to add one.

GPS is on, although the app did not request location rights.

~~/LE: This was removed: https://github.com/spacecowboy/NotePad/issues/270#issuecomment-61608354 ?~~

/LE: Using the app from the PlayStore does list location as a permission needed, although I can't see a why to add one as a reminder though.

And another issue, trying to install the PlayStore downloaded app on a non-GoogleServices enabled device fails ( not sure if because of this, aka it forcefully needs Google Maps ? ) although I do have location services via https://github.com/microg/android_packages_apps_UnifiedNlp and other apps like SatStat ( via F-Droid ) or City Maps 2Go Pro ( via Amazon ) can use location services.

**Comment by spacecowboy** [comment]
You can't use the PlayServices version on non-GoogleServices devices since it require the PlayServices framework which is only distributed on phones with the Play store. This is why there is a "Free"-version, which is also availabe on F-Droid.

PlayServices provides the unified location handling (e.g., Wifi, Cell network, and GPS). Without it, you basically have to code all of that yourself.

To add a location reminder, add a reminder, then press the little alarm clock on the left. It will open a menu and you can select location instead.

**Comment by licaon-kter** [comment]
Looks like it will have to wait until GmsCore is ready: https://fralef.me/using-android-without-google-apps.html

**Comment by spacecowboy** [comment]
Cool. When it's more mature, I might be able to ditch most Google parts on my phone as well.

**Comment by licaon-kter** [comment]
BTW, on a GoogleServices enable device it works as expected, but maybe it's a good idea to make it more visible: clicking on the Add reminder icon/text should yield the menu ( Date / Location ) that one gets when clicking on the *little alarm clock on the left*.

**Comment by spacecowboy** [comment]
Agreed, it's a bit non-intuitive atm.
