### ISSUE TITLE
Repeat every x week or x month, etc

### ISSUE THREAD

**Issue by urmomsangus** [spacecowboy/NotePad#477]
**Is your feature request related to a problem? Please describe.**

It looks like from #281 that this was once an option? It would be nice to have custom intervals of task repeatability.

**Describe the solution you'd like**

Implement the feature and also provide documentation on how the reminders work. (I believe I have figured out that if you click on a day and highlight the day of the reminder then that reminder will only pop up on those days and repeat on those days, is that correct?)

**Additional context**

Nothing really. This app is spectacular and I can't thank you enough for reviving it. It is way simpler to use than any comparable Tasks app on F-Droid. A million thanks to you.

**Comment by CampelloManuel** [comment]
Hi, thank you for reaching out

> It looks like from https://github.com/spacecowboy/NotePad/issues/281 that this was once an option?

yes, we closed all old issues when I picked up the project (24 october 2022) and I still have to take a look and re-open the valid ones. Since I made many changes to the codebase we assumed that most of those issues were (or would become) obsolete. I just re-opened #281 because I agree that your idea is good to implement.

> It would be nice to have custom intervals of task repeatability

Since we are now free from google tasks constraints (#474) we CAN implement this. BUT! 
I suspect this would require a significant modification of the database structure, which will take a lot of time to do and test.

> and also provide documentation on how the reminders work

fair enough. Did you see those circles that pop up the first time you open the app ? I think I will also add one to the "reminder view", the one with the week days, to explain how it works. Do you think it would be a good idea ?

> if you click on a day and highlight the day of the reminder then that reminder will only pop up on those days and repeat on those days, is that correct?

yes, then you just swipe away the notification and the app automatically sets a new reminder on the next selected day, at the same hour. Very useful to make a "weekly" routine, in my experience.

**Comment by urmomsangus** [comment]
>
> I just re-opened #281 because I agree that your idea is good to implement.

It's completely up to you, but if you assign any priority to this, I would suggest making it low priority since the app works fine as it is and users can work around this feature.

Especially because of what you mentioned here :

> I suspect this would require a significant modification of the database structure, which will take a lot of time to do and test.

> 
> fair enough. Did you see those circles that pop up the first time you open the app ? I think I will also add one to the "reminder view", the one with the week days, to explain how it works. Do you think it would be a good idea ?

Yes, I saw the circles and adding something to reminder view would probably be helpful. But honestly, I think instead of adding more code into the app, maybe just add some brief Wiki documentation or adding it to the FAQ would work as well.

> yes, then you just swipe away the notification and the app automatically sets a new reminder on the next selected day, at the same hour. Very useful to make a "weekly" routine, in my experience.

Thanks again! I'm not sure if you want me to leave this issue open for any reason, so I will for now.

**Comment by CampelloManuel** [comment]
I'll close this because I track the monthly reminders and wiki in #387

**Comment by CampelloManuel** [comment]
@urmomsangus I wrote a tutorial for this app
https://github.com/spacecowboy/NotePad/blob/master/documents/TUTORIAL.md
please read it and tell me what you think. 
If it is good, I'll add a link to it on the app in the future.

**Comment by urmomsangus** [comment]
@CampelloManuel the tutorial looks excellent.

I might have to open another issue after reading the documentation: my reminder notifications have no "snooze" or "completed" options despite enabling all notification options.

**Comment by CampelloManuel** [comment]
maybe it shows up only on newer android versions. 
My tablet has android 6.0 and i don't have them.
Can you tell me your OS version and phone model ?

**Comment by urmomsangus** [comment]
> maybe it shows up only on newer android versions. My tablet has android 6.0 and i don't have them. Can you tell me your OS version and phone model ?

Samsung Galaxy A53, Android 12

I was kind of wondering if it is something that got lost in previous versions over time

**Comment by CampelloManuel** [comment]
then it's a bug. please open a new issue for bug reports. 
I will try to investigate why it happens

**Comment by CampelloManuel** [comment]
Continues in #478
